### ISSUE TITLE
Free repair cheat, not limited max stack, bug with lifetime

### ISSUE THREAD

**Issue by bosapara** [ac-minetest/basic_shop#1]
- With 2 pickaxes, you can repair the second one for free. Take a new pick and enter the /sell 1 1, the second one will be repaired for free.

- Stacks not limited, players can sell 3168 items just with '1 shop'

- Unlimited 'time left' works for all types of traders, should be only for Pro.

**Comment by ac-minetest** [comment]
fixed: 
1. > Unlimited 'time left' works for all types of traders, should be only for Pro.

debate: 
1. > Stacks not limited, players can sell 3168 items just with '1 shop'

  If i have 3000 diamonds, why can't i sell them? Doesn't sound reasonable. They are my diamonds, i can do what i want?

2. > With 2 pickaxes, you can repair the second one for free. Take a new pick and enter the /sell 1 1, the second one will be repaired for free.

 When you tell 'minetest' to take 1 pick from inventory, it DOESNT check what wear pick has, it just takes it. I prohibited selling worn out picks but minetest does not care if some other pick you have has wear. 1 possible 'solution' would be to look ALL ITEMS in inventory, if it is pick and has wear don't allow sell and tell player to put it out of inventory before selling. FIXED - but its not nice.

**Comment by bosapara** [comment]
`>If i have 3000 diamonds, why can't i sell them?`

The store is turning into not valuable place to sell things. Any noob can sell <3168 items. I prefer limited version, IMHO. 

`>When you tell 'minetest' to take 1 pick from inventory...`
Better solution - selling wear things only from current hand (player:get_wielded_item())

_______________________

New issue - /shop_set_money wont work with names: test_123 or similar

fix:
```
pname,amount = string.match(param,"^([^ ]+) +(.+)$");
if not pname or not tonumber(amount) then minetest.chat_send_player(name,"usage: shop_set_money NAME AMOUNT") return end
```


______________________

Price should be too - "price = math.floor(price+0.5)"

______________________

Sometimes crash happens by the reason of left button (or wrong number of pages)
`Lua: Runtime error from mod 'basic_shop' in callback on playerReveiveFields():/basic_shop/init.lua:218: attempt to invex a nil value`
